name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: prebuild
      run: |
        add-apt-repository -y ppa:ubuntu-toolchain-r/test
        apt-get update
        apt-get -y install gcc-7 g++-7 libboost-all-dev
        update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 1
        update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 1
    - name: run build
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
